# mysql -h localhost -u root -p

version: "3"

services:
  mysqlsrv:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "nicedb"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
